version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: kanban-lite-db
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
    container_name: kanban-lite-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/kanban
      AUTO_MIGRATE: "true"
      FRONTEND_ORIGIN: http://localhost:5173
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend/app:/app/app
      - ./backend/alembic:/app/alembic
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/scripts:/app/scripts

  web:
    build:
      context: ./web
      target: development
    container_name: kanban-lite-web
    command: npm run dev -- --host 0.0.0.0 --port 5173
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./web:/app
      - /app/node_modules

volumes:
  pgdata:
