services:
  - type: web
    name: kanban-lite-api
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: AUTO_MIGRATE
        value: "true"
      - key: FRONTEND_ORIGIN
        sync: false
      - key: ADDITIONAL_ORIGINS
        sync: false
  - type: web
    name: kanban-lite-web
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    rootDir: web
    envVars:
      - key: VITE_API_URL
        sync: false
databases:
  - name: kanban-db
    plan: free
