export default function AboutPage() {
  return (
    <section className="mx-auto max-w-3xl space-y-4 text-slate-200">
      <h1 className="text-3xl font-semibold text-white">About Kanban Lite</h1>
      <p>
        Kanban Lite is a focused kanban board designed for small teams that want a fast way to
        track work across Todo, Doing, and Done. It is built with FastAPI, PostgreSQL, and a
        mobile-first React experience powered by React Query and drag-and-drop.
      </p>
      <p>
        The project ships with local Docker orchestration, automated tests, and a Render blueprint
        so you can deploy quickly. Use the board to create, edit, reorder, and archive tasks while
        keeping the flow of work transparent across devices.
      </p>
      <p>
        Generated by Codex (OpenAI) with instructions from discussions between Chatgpt and Thiago Pagogna
      </p>
    </section>
  );
}
